# Generated by Django 2.1.1 on 2018-09-22 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='au',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books.Authors', verbose_name='作者名稱'),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='trans',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books.Translators', verbose_name='譯者名稱'),
        ),
    ]
