# Generated by Django 2.1.1 on 2018-09-22 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20180922_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinfo',
            old_name='thrid_category',
            new_name='third_category',
        ),
    ]
