# Generated by Django 2.1.2 on 2018-10-06 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='作者ID')),
                ('author_ch', models.CharField(max_length=15, verbose_name='作者中文名')),
                ('author_fore', models.CharField(max_length=50, verbose_name='作者外文名')),
                ('author_intro', models.TextField(verbose_name='作者簡介')),
            ],
            options={
                'db_table': 'authors',
                'ordering': ['_id'],
            },
        ),
        migrations.CreateModel(
            name='Bookinfo',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='書籍ID')),
                ('book_image', models.TextField(verbose_name='書籍圖片')),
                ('book_name_ch', models.CharField(max_length=50, verbose_name='中文書名')),
                ('book_name_fore', models.CharField(max_length=100, verbose_name='外文書名')),
                ('publisher', models.CharField(max_length=30, verbose_name='出版社')),
                ('pub_time', models.CharField(max_length=10, verbose_name='出版日期')),
                ('pub_contry', models.CharField(max_length=15, verbose_name='出版地')),
                ('isbn', models.CharField(max_length=20, verbose_name='ISBN編碼')),
                ('pub_category', models.CharField(max_length=20, verbose_name='出版社分類')),
                ('first_category', models.CharField(max_length=20, verbose_name='分類第一層')),
                ('second_category', models.CharField(max_length=20, verbose_name='分類第二層')),
                ('third_category', models.CharField(max_length=20, verbose_name='分類第三層')),
                ('spec', models.CharField(max_length=50, verbose_name='書籍規格')),
                ('lang', models.CharField(max_length=15, verbose_name='書籍語言')),
                ('content', models.TextField(verbose_name='書籍內容')),
                ('table_of_content', models.TextField(verbose_name='書籍目錄')),
                ('au', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books.Authors', verbose_name='作者名稱')),
            ],
            options={
                'db_table': 'bookinfo',
                'ordering': ['_id'],
            },
        ),
        migrations.CreateModel(
            name='Translators',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='譯者ID')),
                ('translator_name', models.CharField(max_length=15, verbose_name='譯者姓名')),
                ('translator_intro', models.TextField(verbose_name='譯者簡介')),
            ],
            options={
                'db_table': 'translators',
                'ordering': ['_id'],
            },
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='trans',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books.Translators', verbose_name='譯者名稱'),
        ),
    ]
