# Generated by Django 2.1.2 on 2018-10-06 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='用戶名稱')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='電子郵件')),
                ('user_image', models.ImageField(blank=True, upload_to='img', verbose_name='用戶圖片')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('gender', models.CharField(blank=True, choices=[('Male', '男'), ('Female', '女')], max_length=5, null=True, verbose_name='性別')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='地區')),
                ('about', models.TextField(blank=True, null=True, verbose_name='關於我')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jwt_secret', models.UUIDField(default=uuid.uuid4)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Bookshelf',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='書櫃ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bookinfo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Bookinfo', verbose_name='書籍')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用戶ID')),
            ],
            options={
                'db_table': 'bookshelf',
                'ordering': ['_id'],
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='評論ID')),
                ('comment_text', models.TextField(blank=True, verbose_name='評論文字')),
                ('rating', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=1, verbose_name='評分')),
                ('read_status', models.IntegerField(choices=[(1, '想讀'), (2, '閱讀中'), (3, '已讀完')], default=1, verbose_name='閱讀狀態')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bookinfo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Bookinfo', verbose_name='書籍ID')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用戶ID')),
            ],
            options={
                'db_table': 'comments',
                'ordering': ['_id'],
            },
        ),
    ]
