# Generated by Django 2.1.2 on 2018-10-07 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='bookinfo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books.Bookinfo', verbose_name='書籍ID'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用戶ID'),
        ),
    ]
