# Generated by Django 2.1.1 on 2018-10-05 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('accounts', '0005_uniuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookshelf',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='書櫃ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('bookinfo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Bookinfo', verbose_name='書籍')),
            ],
            options={
                'db_table': 'bookshelf',
                'ordering': ['_id'],
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='評論ID')),
                ('comment_text', models.TextField(blank=True, verbose_name='評論文字')),
                ('rating', models.IntegerField(blank=True, verbose_name='評分')),
                ('read_status', models.CharField(blank=True, choices=[('Intend', '想讀'), ('Reading', '閱讀中'), ('Done', '已讀完')], max_length=10, verbose_name='閱讀狀態')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('bookinfo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Bookinfo', verbose_name='書籍ID')),
            ],
            options={
                'db_table': 'comments',
                'ordering': ['_id'],
            },
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用戶ID'),
        ),
        migrations.AddField(
            model_name='bookshelf',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用戶ID'),
        ),
    ]
